# Generated by Django 5.0.6 on 2024-05-18 12:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('gacci', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paciente',
            name='numero',
            field=models.CharField(default='', max_length=10),
        ),
    ]
