# Generated by Django 5.0.6 on 2024-05-17 14:06

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('endereco', models.CharField(max_length=150)),
                ('numero', models.CharField(default='', max_length=50)),
                ('bairro', models.CharField(max_length=100, null=True)),
                ('idade', models.CharField(default='', max_length=50)),
                ('data_nascimento', models.DateTimeField(default=datetime.datetime.now)),
                ('telefone', models.CharField(max_length=50, null=True)),
                ('rg', models.CharField(default='', max_length=50)),
                ('cpf', models.CharField(default='', max_length=50)),
                ('local_trabalho', models.CharField(max_length=50, null=True)),
                ('grau_instrucao', models.CharField(choices=[('SEM INSTRUÇÃO', 'Sem Instrução'), ('FUNDAMENTAL INCOMPLETO', 'Fundamental Incompleto'), ('FUNDAMENTAL COMPLETO', 'Fundamental Completo'), ('MÉDIO INCOMPLETO', 'Médio Incompleto'), ('MÉDIO COMPLETO', 'Médio Completo'), ('SUPERIOR INCOMPLETO', 'Superior Incompleto'), ('SUPERIOR COMPLETO', 'Superior Completo')], default='', max_length=100)),
                ('renda_mensal', models.CharField(default='', max_length=50)),
                ('estado_civil', models.CharField(choices=[('SOLTEIRO', 'Solteiro'), ('CASADO', 'Casado'), ('UNIÃO ESTÁVEL', 'União Estável'), ('SEPARADO', 'Separado'), ('DIVORCIADO', 'Divorciado'), ('VIÚVO', 'Viúvo')], default='', max_length=100)),
                ('auxilio_solicitado', models.CharField(choices=[('CESTA BÁSICA', 'Cesta Básica'), ('LEITE', 'Leite'), ('SUPLEMENTO', 'Suplemento'), ('MEDICAMENTOS', 'Medicamentos'), ('OUTROS', 'Outros')], default='', max_length=100)),
                ('composicao_familiar', models.TextField(default='')),
                ('habitacao', models.CharField(choices=[('PRÓPRIA', 'Própria'), ('ALUGADA', 'Alugada'), ('FINANCIADA', 'Financiada'), ('CEDIDA', 'Cedida')], default='', max_length=100)),
                ('valor_habitacao', models.CharField(default='', max_length=50)),
                ('saude', models.CharField(choices=[('INSS', 'INSS'), ('FUNERAL', 'Funeral'), ('OUTRA', 'Outra')], default='', max_length=100)),
                ('saude_familia', models.CharField(default='', max_length=255)),
                ('diagnostico', models.CharField(default='', max_length=255)),
                ('providencia', models.CharField(default='', max_length=255)),
                ('publicada', models.BooleanField(default=True)),
                ('data', models.DateTimeField(default=datetime.datetime.now)),
                ('observacao', models.TextField(default='')),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
